import type { Metadata } from "next";
import { Montserrat, Montserrat_Alternates } from "next/font/google";
import "modern-normalize/modern-normalize.css";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import Hero from '@/components/Hero/Hero'
const montserratSans = Montserrat({
  variable: "--font-sans",
  subsets: ["latin", "cyrillic"],
  weight: ["400", "500", "600"],
});

const montserratDisplay = Montserrat_Alternates({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <body
        className={`${montserratSans.variable} ${montserratDisplay.variable} antialiased`}
      >
        <Header />
      

        <main>{children}</main>

        <Footer />
      </body>
    </html>
  );
}
